# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinFeedAPIStockRESTAPI.Model.ModelsAdminMessageModel do
  @moduledoc """
  Represents the response DTO for IEX admin information, combining all symbol-based admin message types
  """

  @derive JSON.Encoder
  defstruct [
    :trading_status,
    :official_price,
    :security_event,
    :auction_information,
    :short_sale_price_test,
    :operational_halt_status,
    :retail_liquidity_indicator,
    :system_event,
    :security_directory
  ]

  @type t :: %__MODULE__{
    :trading_status => FinFeedAPIStockRESTAPI.Model.ModelsTradingStatusModel.t | nil,
    :official_price => FinFeedAPIStockRESTAPI.Model.ModelsOfficialPriceModel.t | nil,
    :security_event => FinFeedAPIStockRESTAPI.Model.ModelsSecurityEventModel.t | nil,
    :auction_information => FinFeedAPIStockRESTAPI.Model.ModelsAuctionInformationModel.t | nil,
    :short_sale_price_test => FinFeedAPIStockRESTAPI.Model.ModelsShortSalePriceTestStatusModel.t | nil,
    :operational_halt_status => FinFeedAPIStockRESTAPI.Model.ModelsOperationalHaltStatusModel.t | nil,
    :retail_liquidity_indicator => FinFeedAPIStockRESTAPI.Model.ModelsRetailLiquidityIndicatorModel.t | nil,
    :system_event => FinFeedAPIStockRESTAPI.Model.IexSystemEventSystemEventModel.t | nil,
    :security_directory => FinFeedAPIStockRESTAPI.Model.ModelsSecurityDirectoryModel.t | nil
  }

  alias FinFeedAPIStockRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:trading_status, :struct, FinFeedAPIStockRESTAPI.Model.ModelsTradingStatusModel)
     |> Deserializer.deserialize(:official_price, :struct, FinFeedAPIStockRESTAPI.Model.ModelsOfficialPriceModel)
     |> Deserializer.deserialize(:security_event, :struct, FinFeedAPIStockRESTAPI.Model.ModelsSecurityEventModel)
     |> Deserializer.deserialize(:auction_information, :struct, FinFeedAPIStockRESTAPI.Model.ModelsAuctionInformationModel)
     |> Deserializer.deserialize(:short_sale_price_test, :struct, FinFeedAPIStockRESTAPI.Model.ModelsShortSalePriceTestStatusModel)
     |> Deserializer.deserialize(:operational_halt_status, :struct, FinFeedAPIStockRESTAPI.Model.ModelsOperationalHaltStatusModel)
     |> Deserializer.deserialize(:retail_liquidity_indicator, :struct, FinFeedAPIStockRESTAPI.Model.ModelsRetailLiquidityIndicatorModel)
     |> Deserializer.deserialize(:system_event, :struct, FinFeedAPIStockRESTAPI.Model.IexSystemEventSystemEventModel)
     |> Deserializer.deserialize(:security_directory, :struct, FinFeedAPIStockRESTAPI.Model.ModelsSecurityDirectoryModel)
  end
end

