/**
 * CoinAPI Market Data REST API
 * Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MarketDataMetadata_Chain.h
 *
 * Represents a blockchain chain.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MarketDataMetadata_Chain_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MarketDataMetadata_Chain_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Represents a blockchain chain.
/// </summary>
class  MarketDataMetadata_Chain
    : public ModelBase
{
public:
    MarketDataMetadata_Chain();
    virtual ~MarketDataMetadata_Chain();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// MarketDataMetadata_Chain members


    /// <summary>
    /// Gets or sets the chain identifier.
    /// </summary>
    utility::string_t getChainId() const;
    bool chainIdIsSet() const;
    void unsetChain_id();
    void setChainId(const utility::string_t& value);

    /// <summary>
    /// Gets or sets the name of the chain.
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);


protected:
    boost::optional<utility::string_t> m_Chain_id;

    boost::optional<utility::string_t> m_Name;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MarketDataMetadata_Chain_H_ */
