# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinFeedAPIStockRESTAPI.Api.NativeIEX do
  @moduledoc """
  API calls for all endpoints tagged `NativeIEX`.
  """

  alias FinFeedAPIStockRESTAPI.Connection
  import FinFeedAPIStockRESTAPI.RequestBuilder

  @doc """
  Get Admin Messages
  Streaming endpoint. Use `limit` to cap the number of records returned (default 100, max 10000).

  ### Parameters

  - `connection` (FinFeedAPIStockRESTAPI.Connection): Connection to server
  - `symbol` (String.t): The symbol identifier
  - `date` (DateTime.t): Date in format YYYY-MM-DD
  - `opts` (keyword): Optional parameters
    - `:limit` (integer()): Maximum number of records to return (1-10000, default 100)

  ### Returns

  - `{:ok, [%ModelsAdminMessageModel{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_native_iex_admin_messages_symbol_get(Tesla.Env.client, String.t, DateTime.t, keyword()) :: {:ok, [FinFeedAPIStockRESTAPI.Model.ModelsAdminMessageModel.t]} | {:error, Tesla.Env.t}
  def v1_native_iex_admin_messages_symbol_get(connection, symbol, date, opts \\ []) do
    optional_params = %{
      :limit => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/native/iex/admin/messages/#{symbol}")
      |> add_param(:query, :date, date)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, FinFeedAPIStockRESTAPI.Model.ModelsAdminMessageModel}
    ])
  end

  @doc """
  Get System Events
  Streaming endpoint. Use `limit` to cap the number of records returned (default 100, max 10000).

  ### Parameters

  - `connection` (FinFeedAPIStockRESTAPI.Connection): Connection to server
  - `date` (DateTime.t): Date in format YYYY-MM-DD
  - `opts` (keyword): Optional parameters
    - `:limit` (integer()): Maximum number of records to return (1-10000, default 100)

  ### Returns

  - `{:ok, [%IexSystemEventSystemEventModel{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_native_iex_admin_system_event_get(Tesla.Env.client, DateTime.t, keyword()) :: {:ok, [FinFeedAPIStockRESTAPI.Model.IexSystemEventSystemEventModel.t]} | {:error, Tesla.Env.t}
  def v1_native_iex_admin_system_event_get(connection, date, opts \\ []) do
    optional_params = %{
      :limit => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/native/iex/admin/system-event")
      |> add_param(:query, :date, date)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, FinFeedAPIStockRESTAPI.Model.IexSystemEventSystemEventModel}
    ])
  end

  @doc """
  Get Level-1 Quotes
  Streaming endpoint. Use `limit` to cap the number of records returned (default 100, max 10000).

  ### Parameters

  - `connection` (FinFeedAPIStockRESTAPI.Connection): Connection to server
  - `symbol` (String.t): The symbol identifier
  - `date` (DateTime.t): Date in format YYYY-MM-DD
  - `opts` (keyword): Optional parameters
    - `:limit` (integer()): Maximum number of records to return (1-10000, default 100)

  ### Returns

  - `{:ok, [%IexQuoteUpdateQuoteUpdateModel{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_native_iex_level1_quote_symbol_get(Tesla.Env.client, String.t, DateTime.t, keyword()) :: {:ok, [FinFeedAPIStockRESTAPI.Model.IexQuoteUpdateQuoteUpdateModel.t]} | {:error, Tesla.Env.t}
  def v1_native_iex_level1_quote_symbol_get(connection, symbol, date, opts \\ []) do
    optional_params = %{
      :limit => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/native/iex/level1-quote/#{symbol}")
      |> add_param(:query, :date, date)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, FinFeedAPIStockRESTAPI.Model.IexQuoteUpdateQuoteUpdateModel}
    ])
  end

  @doc """
  Get Level-2 Price Level Book
  Streaming endpoint. Use `limit` to cap the number of records returned (default 100, max 10000).

  ### Parameters

  - `connection` (FinFeedAPIStockRESTAPI.Connection): Connection to server
  - `symbol` (String.t): The symbol identifier
  - `date` (DateTime.t): Date in format YYYY-MM-DD
  - `opts` (keyword): Optional parameters
    - `:limit` (integer()): Maximum number of records to return (1-10000, default 100)

  ### Returns

  - `{:ok, [%IexPriceLevelUpdatePriceLevelUpdateModel{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_native_iex_level2_price_level_update_symbol_get(Tesla.Env.client, String.t, DateTime.t, keyword()) :: {:ok, [FinFeedAPIStockRESTAPI.Model.IexPriceLevelUpdatePriceLevelUpdateModel.t]} | {:error, Tesla.Env.t}
  def v1_native_iex_level2_price_level_update_symbol_get(connection, symbol, date, opts \\ []) do
    optional_params = %{
      :limit => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/native/iex/level2-price-level-update/#{symbol}")
      |> add_param(:query, :date, date)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, FinFeedAPIStockRESTAPI.Model.IexPriceLevelUpdatePriceLevelUpdateModel}
    ])
  end

  @doc """
  Get Level-3 Order Book
  Streaming endpoint. Use `limit` to cap the number of records returned (default 100, max 10000).

  ### Parameters

  - `connection` (FinFeedAPIStockRESTAPI.Connection): Connection to server
  - `symbol` (String.t): The symbol identifier
  - `date` (DateTime.t): Date in format YYYY-MM-DD
  - `opts` (keyword): Optional parameters
    - `:limit` (integer()): Maximum number of records to return (1-10000, default 100)

  ### Returns

  - `{:ok, [%ModelsOrderBookModel{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_native_iex_level3_order_book_symbol_get(Tesla.Env.client, String.t, DateTime.t, keyword()) :: {:ok, [FinFeedAPIStockRESTAPI.Model.ModelsOrderBookModel.t]} | {:error, Tesla.Env.t}
  def v1_native_iex_level3_order_book_symbol_get(connection, symbol, date, opts \\ []) do
    optional_params = %{
      :limit => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/native/iex/level3-order-book/#{symbol}")
      |> add_param(:query, :date, date)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, FinFeedAPIStockRESTAPI.Model.ModelsOrderBookModel}
    ])
  end

  @doc """
  Get Trades
  Streaming endpoint. Use `limit` to cap the number of trade records returned (default 100, max 10000).

  ### Parameters

  - `connection` (FinFeedAPIStockRESTAPI.Connection): Connection to server
  - `symbol` (String.t): The symbol identifier
  - `date` (DateTime.t): Date in format YYYY-MM-DD
  - `opts` (keyword): Optional parameters
    - `:limit` (integer()): Maximum number of records to return (1-10000, default 100)

  ### Returns

  - `{:ok, [%IexTradeTradeModel{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec v1_native_iex_trade_symbol_get(Tesla.Env.client, String.t, DateTime.t, keyword()) :: {:ok, [FinFeedAPIStockRESTAPI.Model.IexTradeTradeModel.t]} | {:error, Tesla.Env.t}
  def v1_native_iex_trade_symbol_get(connection, symbol, date, opts \\ []) do
    optional_params = %{
      :limit => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/native/iex/trade/#{symbol}")
      |> add_param(:query, :date, date)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, FinFeedAPIStockRESTAPI.Model.IexTradeTradeModel}
    ])
  end
end
