/**
 * CoinAPI Market Data REST API
 * Cryptocurrency market data: metadata, quotes, books, trades, OHLCV, rates, metrics, options.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OrderBookApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_OrderBookApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_OrderBookApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/V1_OrderBook.h"
#include "CppRestOpenAPIClient/model/V1_OrderBookBase.h"
#include "CppRestOpenAPIClient/model/V1_OrderBookDepth.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  OrderBookApi 
{
public:

    explicit OrderBookApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~OrderBookApi();

    /// <summary>
    /// Get current order book
    /// </summary>
    /// <remarks>
    /// Retrieves the current order book for the specified symbol.
    /// </remarks>
    /// <param name="symbolId">The symbol ID (from the Metadata -&gt; Symbols)</param>
    /// <param name="limitLevels">The maximum number of levels to include in the response. (optional, default to 0)</param>
    pplx::task<std::shared_ptr<V1_OrderBookBase>> v1OrderbooksSymbolIdCurrentGet(
        utility::string_t symbolId,
        boost::optional<int32_t> limitLevels
    ) const;
    /// <summary>
    /// Current depth of the order book
    /// </summary>
    /// <remarks>
    /// Retrieves the current depth of the order book for the specified symbol.
    /// </remarks>
    /// <param name="symbolId">The symbol ID (from the Metadata -&gt; Symbols)</param>
    /// <param name="limitLevels">The maximum number of levels to include in the response. (optional, default to 0)</param>
    pplx::task<std::shared_ptr<V1_OrderBookDepth>> v1OrderbooksSymbolIdDepthCurrentGet(
        utility::string_t symbolId,
        boost::optional<int32_t> limitLevels
    ) const;
    /// <summary>
    /// Historical data
    /// </summary>
    /// <remarks>
    /// Get historical order book snapshots for a specific symbol within time range, returned in time ascending order.              :::info The historical order book data via the REST API is currently limited by a number of updates and to the maximum number of 50 levels. :::              This endpoint supports hourly granularity for APITP data with automatic fallback to daily data for older records. Timestamps are normalized to hour boundaries, and data is fetched per hour with precise filtering to your exact time range.              :::tip For querying a full day of data, use the &#39;date&#39; parameter. For specific time ranges (including cross-day or multi-hour queries), use &#39;time_start&#39; and &#39;time_end&#39;. :::
    /// </remarks>
    /// <param name="symbolId">Symbol identifier for requested timeseries (from the Metadata -&gt; Symbols)</param>
    /// <param name="date">Date in ISO 8601, returned data is for the whole given day (required if &#39;time_start&#39; is not provided) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="timeStart">Starting time in ISO 8601 (supports hourly precision, e.g., 2026-01-16T11:00:00Z) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="timeEnd">Timeseries ending time in ISO 8601 (optional, supports cross-day queries) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="limit">Amount of items to return (optional, minimum is 1, maximum is 100000, default value is 100, if the parameter is used then every 100 output items are counted as one request) (optional, default to 0)</param>
    /// <param name="limitLevels">Maximum amount of levels from each side of the book to include in response (optional, maximum is 50) (optional, default to 0)</param>
    pplx::task<std::vector<std::shared_ptr<V1_OrderBook>>> v1OrderbooksSymbolIdHistoryGet(
        utility::string_t symbolId,
        boost::optional<utility::string_t> date,
        boost::optional<utility::string_t> timeStart,
        boost::optional<utility::string_t> timeEnd,
        boost::optional<int32_t> limit,
        boost::optional<int32_t> limitLevels
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_OrderBookApi_H_ */

