{-
   FinFeedAPI Stock REST API

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.4
   FinFeedAPI Stock REST API API version: v1
   Contact: support@apibricks.io
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : FinFeedAPIStockREST.API.NativeIEX
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module FinFeedAPIStockREST.API.NativeIEX where

import FinFeedAPIStockREST.Core
import FinFeedAPIStockREST.MimeTypes
import FinFeedAPIStockREST.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** NativeIEX

-- *** v1NativeIexAdminMessagesSymbolGet

-- | @GET \/v1\/native\/iex\/admin\/messages\/{symbol}@
-- 
-- Get Admin Messages
-- 
-- Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.
-- 
-- AuthMethod: 'AuthApiKeyAPIKey', 'AuthBasicJWT'
-- 
v1NativeIexAdminMessagesSymbolGet
  :: Symbol -- ^ "symbol" -  The symbol identifier
  -> FinFeedAPIStockRESTRequest V1NativeIexAdminMessagesSymbolGet MimeNoContent [ModelsAdminMessageModel] MimeJSON
v1NativeIexAdminMessagesSymbolGet (Symbol symbol) =
  _mkRequest "GET" ["/v1/native/iex/admin/messages/",toPath symbol]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyAPIKey)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicJWT)

data V1NativeIexAdminMessagesSymbolGet  

-- | /Optional Param/ "date" - UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
instance HasOptionalParam V1NativeIexAdminMessagesSymbolGet ParamDate where
  applyOptionalParam req (ParamDate xs) =
    req `addQuery` toQuery ("date", Just xs)

-- | /Optional Param/ "time_start" - Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
instance HasOptionalParam V1NativeIexAdminMessagesSymbolGet TimeStart where
  applyOptionalParam req (TimeStart xs) =
    req `addQuery` toQuery ("time_start", Just xs)

-- | /Optional Param/ "limit" - Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
instance HasOptionalParam V1NativeIexAdminMessagesSymbolGet Limit where
  applyOptionalParam req (Limit xs) =
    req `addQuery` toQuery ("limit", Just xs)
-- | @application/json@
instance Produces V1NativeIexAdminMessagesSymbolGet MimeJSON


-- *** v1NativeIexAdminSystemEventGet

-- | @GET \/v1\/native\/iex\/admin\/system-event@
-- 
-- Get System Events
-- 
-- Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.
-- 
-- AuthMethod: 'AuthApiKeyAPIKey', 'AuthBasicJWT'
-- 
v1NativeIexAdminSystemEventGet
  :: FinFeedAPIStockRESTRequest V1NativeIexAdminSystemEventGet MimeNoContent [IEXSystemEventSystemEventModel] MimeJSON
v1NativeIexAdminSystemEventGet =
  _mkRequest "GET" ["/v1/native/iex/admin/system-event"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyAPIKey)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicJWT)

data V1NativeIexAdminSystemEventGet  

-- | /Optional Param/ "date" - UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
instance HasOptionalParam V1NativeIexAdminSystemEventGet ParamDate where
  applyOptionalParam req (ParamDate xs) =
    req `addQuery` toQuery ("date", Just xs)

-- | /Optional Param/ "time_start" - Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
instance HasOptionalParam V1NativeIexAdminSystemEventGet TimeStart where
  applyOptionalParam req (TimeStart xs) =
    req `addQuery` toQuery ("time_start", Just xs)

-- | /Optional Param/ "limit" - Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
instance HasOptionalParam V1NativeIexAdminSystemEventGet Limit where
  applyOptionalParam req (Limit xs) =
    req `addQuery` toQuery ("limit", Just xs)
-- | @application/json@
instance Produces V1NativeIexAdminSystemEventGet MimeJSON


-- *** v1NativeIexLevel1QuoteSymbolGet

-- | @GET \/v1\/native\/iex\/level1-quote\/{symbol}@
-- 
-- Get Level-1 Quotes
-- 
-- Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.
-- 
-- AuthMethod: 'AuthApiKeyAPIKey', 'AuthBasicJWT'
-- 
v1NativeIexLevel1QuoteSymbolGet
  :: Symbol -- ^ "symbol" -  The symbol identifier
  -> FinFeedAPIStockRESTRequest V1NativeIexLevel1QuoteSymbolGet MimeNoContent [IEXQuoteUpdateQuoteUpdateModel] MimeJSON
v1NativeIexLevel1QuoteSymbolGet (Symbol symbol) =
  _mkRequest "GET" ["/v1/native/iex/level1-quote/",toPath symbol]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyAPIKey)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicJWT)

data V1NativeIexLevel1QuoteSymbolGet  

-- | /Optional Param/ "date" - UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
instance HasOptionalParam V1NativeIexLevel1QuoteSymbolGet ParamDate where
  applyOptionalParam req (ParamDate xs) =
    req `addQuery` toQuery ("date", Just xs)

-- | /Optional Param/ "time_start" - Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
instance HasOptionalParam V1NativeIexLevel1QuoteSymbolGet TimeStart where
  applyOptionalParam req (TimeStart xs) =
    req `addQuery` toQuery ("time_start", Just xs)

-- | /Optional Param/ "limit" - Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
instance HasOptionalParam V1NativeIexLevel1QuoteSymbolGet Limit where
  applyOptionalParam req (Limit xs) =
    req `addQuery` toQuery ("limit", Just xs)
-- | @application/json@
instance Produces V1NativeIexLevel1QuoteSymbolGet MimeJSON


-- *** v1NativeIexLevel2PriceLevelUpdateSymbolGet

-- | @GET \/v1\/native\/iex\/level2-price-level-update\/{symbol}@
-- 
-- Get Level-2 Price Level Book
-- 
-- Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.
-- 
-- AuthMethod: 'AuthApiKeyAPIKey', 'AuthBasicJWT'
-- 
v1NativeIexLevel2PriceLevelUpdateSymbolGet
  :: Symbol -- ^ "symbol" -  The symbol identifier
  -> FinFeedAPIStockRESTRequest V1NativeIexLevel2PriceLevelUpdateSymbolGet MimeNoContent [IEXPriceLevelUpdatePriceLevelUpdateModel] MimeJSON
v1NativeIexLevel2PriceLevelUpdateSymbolGet (Symbol symbol) =
  _mkRequest "GET" ["/v1/native/iex/level2-price-level-update/",toPath symbol]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyAPIKey)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicJWT)

data V1NativeIexLevel2PriceLevelUpdateSymbolGet  

-- | /Optional Param/ "date" - UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
instance HasOptionalParam V1NativeIexLevel2PriceLevelUpdateSymbolGet ParamDate where
  applyOptionalParam req (ParamDate xs) =
    req `addQuery` toQuery ("date", Just xs)

-- | /Optional Param/ "time_start" - Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
instance HasOptionalParam V1NativeIexLevel2PriceLevelUpdateSymbolGet TimeStart where
  applyOptionalParam req (TimeStart xs) =
    req `addQuery` toQuery ("time_start", Just xs)

-- | /Optional Param/ "limit" - Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
instance HasOptionalParam V1NativeIexLevel2PriceLevelUpdateSymbolGet Limit where
  applyOptionalParam req (Limit xs) =
    req `addQuery` toQuery ("limit", Just xs)
-- | @application/json@
instance Produces V1NativeIexLevel2PriceLevelUpdateSymbolGet MimeJSON


-- *** v1NativeIexLevel3OrderBookSymbolGet

-- | @GET \/v1\/native\/iex\/level3-order-book\/{symbol}@
-- 
-- Get Level-3 Order Book
-- 
-- Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.
-- 
-- AuthMethod: 'AuthApiKeyAPIKey', 'AuthBasicJWT'
-- 
v1NativeIexLevel3OrderBookSymbolGet
  :: Symbol -- ^ "symbol" -  The symbol identifier
  -> FinFeedAPIStockRESTRequest V1NativeIexLevel3OrderBookSymbolGet MimeNoContent [ModelsOrderBookModel] MimeJSON
v1NativeIexLevel3OrderBookSymbolGet (Symbol symbol) =
  _mkRequest "GET" ["/v1/native/iex/level3-order-book/",toPath symbol]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyAPIKey)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicJWT)

data V1NativeIexLevel3OrderBookSymbolGet  

-- | /Optional Param/ "date" - UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
instance HasOptionalParam V1NativeIexLevel3OrderBookSymbolGet ParamDate where
  applyOptionalParam req (ParamDate xs) =
    req `addQuery` toQuery ("date", Just xs)

-- | /Optional Param/ "time_start" - Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
instance HasOptionalParam V1NativeIexLevel3OrderBookSymbolGet TimeStart where
  applyOptionalParam req (TimeStart xs) =
    req `addQuery` toQuery ("time_start", Just xs)

-- | /Optional Param/ "limit" - Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
instance HasOptionalParam V1NativeIexLevel3OrderBookSymbolGet Limit where
  applyOptionalParam req (Limit xs) =
    req `addQuery` toQuery ("limit", Just xs)
-- | @application/json@
instance Produces V1NativeIexLevel3OrderBookSymbolGet MimeJSON


-- *** v1NativeIexTradeSymbolGet

-- | @GET \/v1\/native\/iex\/trade\/{symbol}@
-- 
-- Get Trades
-- 
-- Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.
-- 
-- AuthMethod: 'AuthApiKeyAPIKey', 'AuthBasicJWT'
-- 
v1NativeIexTradeSymbolGet
  :: Symbol -- ^ "symbol" -  The symbol identifier
  -> FinFeedAPIStockRESTRequest V1NativeIexTradeSymbolGet MimeNoContent [IEXTradeTradeModel] MimeJSON
v1NativeIexTradeSymbolGet (Symbol symbol) =
  _mkRequest "GET" ["/v1/native/iex/trade/",toPath symbol]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyAPIKey)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicJWT)

data V1NativeIexTradeSymbolGet  

-- | /Optional Param/ "date" - UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
instance HasOptionalParam V1NativeIexTradeSymbolGet ParamDate where
  applyOptionalParam req (ParamDate xs) =
    req `addQuery` toQuery ("date", Just xs)

-- | /Optional Param/ "time_start" - Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
instance HasOptionalParam V1NativeIexTradeSymbolGet TimeStart where
  applyOptionalParam req (TimeStart xs) =
    req `addQuery` toQuery ("time_start", Just xs)

-- | /Optional Param/ "limit" - Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
instance HasOptionalParam V1NativeIexTradeSymbolGet Limit where
  applyOptionalParam req (Limit xs) =
    req `addQuery` toQuery ("limit", Just xs)
-- | @application/json@
instance Produces V1NativeIexTradeSymbolGet MimeJSON

