/**
 * FinFeedAPI Stock REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Models_ExecutedOrderModel.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Models_ExecutedOrderModel::Models_ExecutedOrderModel()
{
    m_Timestamp_nanos = 0L;
    m_Timestamp_nanosIsSet = false;
    m_Timestamp = utility::datetime();
    m_TimestampIsSet = false;
    m_Order_id_reference = 0L;
    m_Order_id_referenceIsSet = false;
    m_Sale_condition_flags = 0;
    m_Sale_condition_flagsIsSet = false;
    m_Is_intermarket_sweep = false;
    m_Is_intermarket_sweepIsSet = false;
    m_Is_extended_hours_trade = false;
    m_Is_extended_hours_tradeIsSet = false;
    m_Is_odd_lot_trade = false;
    m_Is_odd_lot_tradeIsSet = false;
    m_Is_trade_through_exempt = false;
    m_Is_trade_through_exemptIsSet = false;
    m_Is_single_price_cross_trade = false;
    m_Is_single_price_cross_tradeIsSet = false;
    m_Size = 0;
    m_SizeIsSet = false;
    m_Price = 0.0;
    m_PriceIsSet = false;
    m_Trade_id = 0L;
    m_Trade_idIsSet = false;
}

Models_ExecutedOrderModel::~Models_ExecutedOrderModel()
{
}

void Models_ExecutedOrderModel::validate()
{
    // TODO: implement validation
}

web::json::value Models_ExecutedOrderModel::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Symbol.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("symbol"))] = ModelBase::toJson(m_Symbol.get());
    }
    if(m_Timestamp_nanosIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("timestamp_nanos"))] = ModelBase::toJson(m_Timestamp_nanos);
    }
    if(m_TimestampIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("timestamp"))] = ModelBase::toJson(m_Timestamp);
    }
    if(m_Order_id_referenceIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("order_id_reference"))] = ModelBase::toJson(m_Order_id_reference);
    }
    if(m_Sale_condition_flagsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("sale_condition_flags"))] = ModelBase::toJson(m_Sale_condition_flags);
    }
    if(m_Is_intermarket_sweepIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_intermarket_sweep"))] = ModelBase::toJson(m_Is_intermarket_sweep);
    }
    if(m_Is_extended_hours_tradeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_extended_hours_trade"))] = ModelBase::toJson(m_Is_extended_hours_trade);
    }
    if(m_Is_odd_lot_tradeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_odd_lot_trade"))] = ModelBase::toJson(m_Is_odd_lot_trade);
    }
    if(m_Is_trade_through_exemptIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_trade_through_exempt"))] = ModelBase::toJson(m_Is_trade_through_exempt);
    }
    if(m_Is_single_price_cross_tradeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_single_price_cross_trade"))] = ModelBase::toJson(m_Is_single_price_cross_trade);
    }
    if(m_SizeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("size"))] = ModelBase::toJson(m_Size);
    }
    if(m_PriceIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("price"))] = ModelBase::toJson(m_Price);
    }
    if(m_Trade_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("trade_id"))] = ModelBase::toJson(m_Trade_id);
    }

    return val;
}

bool Models_ExecutedOrderModel::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("symbol"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("symbol")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSymbol;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSymbol);
            setSymbol(refVal_setSymbol);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("timestamp_nanos"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("timestamp_nanos")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setTimestampNanos;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimestampNanos);
            setTimestampNanos(refVal_setTimestampNanos);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("timestamp"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("timestamp")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTimestamp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimestamp);
            setTimestamp(refVal_setTimestamp);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("order_id_reference"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("order_id_reference")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setOrderIdReference;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOrderIdReference);
            setOrderIdReference(refVal_setOrderIdReference);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("sale_condition_flags"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("sale_condition_flags")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setSaleConditionFlags;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSaleConditionFlags);
            setSaleConditionFlags(refVal_setSaleConditionFlags);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_intermarket_sweep"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_intermarket_sweep")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsIntermarketSweep;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsIntermarketSweep);
            setIsIntermarketSweep(refVal_setIsIntermarketSweep);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_extended_hours_trade"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_extended_hours_trade")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsExtendedHoursTrade;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsExtendedHoursTrade);
            setIsExtendedHoursTrade(refVal_setIsExtendedHoursTrade);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_odd_lot_trade"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_odd_lot_trade")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsOddLotTrade;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsOddLotTrade);
            setIsOddLotTrade(refVal_setIsOddLotTrade);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_trade_through_exempt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_trade_through_exempt")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsTradeThroughExempt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsTradeThroughExempt);
            setIsTradeThroughExempt(refVal_setIsTradeThroughExempt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_single_price_cross_trade"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_single_price_cross_trade")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsSinglePriceCrossTrade;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsSinglePriceCrossTrade);
            setIsSinglePriceCrossTrade(refVal_setIsSinglePriceCrossTrade);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("size"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("size")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setSize;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSize);
            setSize(refVal_setSize);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("price"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("price")));
        if(!fieldValue.is_null())
        {
            double refVal_setPrice;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPrice);
            setPrice(refVal_setPrice);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("trade_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("trade_id")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setTradeId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTradeId);
            setTradeId(refVal_setTradeId);
            
        }
    }
    return ok;
}

void Models_ExecutedOrderModel::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Symbol.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("symbol")), m_Symbol.get()));
    }
    if(m_Timestamp_nanosIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("timestamp_nanos")), m_Timestamp_nanos));
    }
    if(m_TimestampIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("timestamp")), m_Timestamp));
    }
    if(m_Order_id_referenceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("order_id_reference")), m_Order_id_reference));
    }
    if(m_Sale_condition_flagsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("sale_condition_flags")), m_Sale_condition_flags));
    }
    if(m_Is_intermarket_sweepIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_intermarket_sweep")), m_Is_intermarket_sweep));
    }
    if(m_Is_extended_hours_tradeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_extended_hours_trade")), m_Is_extended_hours_trade));
    }
    if(m_Is_odd_lot_tradeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_odd_lot_trade")), m_Is_odd_lot_trade));
    }
    if(m_Is_trade_through_exemptIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_trade_through_exempt")), m_Is_trade_through_exempt));
    }
    if(m_Is_single_price_cross_tradeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_single_price_cross_trade")), m_Is_single_price_cross_trade));
    }
    if(m_SizeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("size")), m_Size));
    }
    if(m_PriceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("price")), m_Price));
    }
    if(m_Trade_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("trade_id")), m_Trade_id));
    }
}

bool Models_ExecutedOrderModel::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("symbol"))))
    {
        utility::string_t refVal_setSymbol;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("symbol"))), refVal_setSymbol );
        setSymbol(refVal_setSymbol);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("timestamp_nanos"))))
    {
        int64_t refVal_setTimestampNanos;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("timestamp_nanos"))), refVal_setTimestampNanos );
        setTimestampNanos(refVal_setTimestampNanos);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("timestamp"))))
    {
        utility::datetime refVal_setTimestamp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("timestamp"))), refVal_setTimestamp );
        setTimestamp(refVal_setTimestamp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("order_id_reference"))))
    {
        int64_t refVal_setOrderIdReference;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("order_id_reference"))), refVal_setOrderIdReference );
        setOrderIdReference(refVal_setOrderIdReference);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("sale_condition_flags"))))
    {
        int32_t refVal_setSaleConditionFlags;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("sale_condition_flags"))), refVal_setSaleConditionFlags );
        setSaleConditionFlags(refVal_setSaleConditionFlags);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_intermarket_sweep"))))
    {
        bool refVal_setIsIntermarketSweep;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_intermarket_sweep"))), refVal_setIsIntermarketSweep );
        setIsIntermarketSweep(refVal_setIsIntermarketSweep);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_extended_hours_trade"))))
    {
        bool refVal_setIsExtendedHoursTrade;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_extended_hours_trade"))), refVal_setIsExtendedHoursTrade );
        setIsExtendedHoursTrade(refVal_setIsExtendedHoursTrade);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_odd_lot_trade"))))
    {
        bool refVal_setIsOddLotTrade;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_odd_lot_trade"))), refVal_setIsOddLotTrade );
        setIsOddLotTrade(refVal_setIsOddLotTrade);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_trade_through_exempt"))))
    {
        bool refVal_setIsTradeThroughExempt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_trade_through_exempt"))), refVal_setIsTradeThroughExempt );
        setIsTradeThroughExempt(refVal_setIsTradeThroughExempt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_single_price_cross_trade"))))
    {
        bool refVal_setIsSinglePriceCrossTrade;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_single_price_cross_trade"))), refVal_setIsSinglePriceCrossTrade );
        setIsSinglePriceCrossTrade(refVal_setIsSinglePriceCrossTrade);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("size"))))
    {
        int32_t refVal_setSize;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("size"))), refVal_setSize );
        setSize(refVal_setSize);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("price"))))
    {
        double refVal_setPrice;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("price"))), refVal_setPrice );
        setPrice(refVal_setPrice);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("trade_id"))))
    {
        int64_t refVal_setTradeId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("trade_id"))), refVal_setTradeId );
        setTradeId(refVal_setTradeId);
    }
    return ok;
}


utility::string_t Models_ExecutedOrderModel::getSymbol() const
{
    return m_Symbol.get();
}


void Models_ExecutedOrderModel::setSymbol(const utility::string_t& value)
{
    m_Symbol = value;
}

bool Models_ExecutedOrderModel::symbolIsSet() const
{
    return m_Symbol.has_value();
}

void Models_ExecutedOrderModel::unsetSymbol()
{
    m_Symbol.reset();
}
int64_t Models_ExecutedOrderModel::getTimestampNanos() const
{
    return m_Timestamp_nanos;
}

void Models_ExecutedOrderModel::setTimestampNanos(int64_t value)
{
    m_Timestamp_nanos = value;
    m_Timestamp_nanosIsSet = true;
}

bool Models_ExecutedOrderModel::timestampNanosIsSet() const
{
    return m_Timestamp_nanosIsSet;
}

void Models_ExecutedOrderModel::unsetTimestamp_nanos()
{
    m_Timestamp_nanosIsSet = false;
}
utility::datetime Models_ExecutedOrderModel::getTimestamp() const
{
    return m_Timestamp;
}


void Models_ExecutedOrderModel::setTimestamp(const utility::datetime& value)
{
    m_Timestamp = value;
    m_TimestampIsSet = true;
}

bool Models_ExecutedOrderModel::timestampIsSet() const
{
    return m_TimestampIsSet;
}

void Models_ExecutedOrderModel::unsetTimestamp()
{
    m_TimestampIsSet = false;
}
int64_t Models_ExecutedOrderModel::getOrderIdReference() const
{
    return m_Order_id_reference;
}

void Models_ExecutedOrderModel::setOrderIdReference(int64_t value)
{
    m_Order_id_reference = value;
    m_Order_id_referenceIsSet = true;
}

bool Models_ExecutedOrderModel::orderIdReferenceIsSet() const
{
    return m_Order_id_referenceIsSet;
}

void Models_ExecutedOrderModel::unsetOrder_id_reference()
{
    m_Order_id_referenceIsSet = false;
}
int32_t Models_ExecutedOrderModel::getSaleConditionFlags() const
{
    return m_Sale_condition_flags;
}

void Models_ExecutedOrderModel::setSaleConditionFlags(int32_t value)
{
    m_Sale_condition_flags = value;
    m_Sale_condition_flagsIsSet = true;
}

bool Models_ExecutedOrderModel::saleConditionFlagsIsSet() const
{
    return m_Sale_condition_flagsIsSet;
}

void Models_ExecutedOrderModel::unsetSale_condition_flags()
{
    m_Sale_condition_flagsIsSet = false;
}
bool Models_ExecutedOrderModel::isIsIntermarketSweep() const
{
    return m_Is_intermarket_sweep;
}

void Models_ExecutedOrderModel::setIsIntermarketSweep(bool value)
{
    m_Is_intermarket_sweep = value;
    m_Is_intermarket_sweepIsSet = true;
}

bool Models_ExecutedOrderModel::isIntermarketSweepIsSet() const
{
    return m_Is_intermarket_sweepIsSet;
}

void Models_ExecutedOrderModel::unsetIs_intermarket_sweep()
{
    m_Is_intermarket_sweepIsSet = false;
}
bool Models_ExecutedOrderModel::isIsExtendedHoursTrade() const
{
    return m_Is_extended_hours_trade;
}

void Models_ExecutedOrderModel::setIsExtendedHoursTrade(bool value)
{
    m_Is_extended_hours_trade = value;
    m_Is_extended_hours_tradeIsSet = true;
}

bool Models_ExecutedOrderModel::isExtendedHoursTradeIsSet() const
{
    return m_Is_extended_hours_tradeIsSet;
}

void Models_ExecutedOrderModel::unsetIs_extended_hours_trade()
{
    m_Is_extended_hours_tradeIsSet = false;
}
bool Models_ExecutedOrderModel::isIsOddLotTrade() const
{
    return m_Is_odd_lot_trade;
}

void Models_ExecutedOrderModel::setIsOddLotTrade(bool value)
{
    m_Is_odd_lot_trade = value;
    m_Is_odd_lot_tradeIsSet = true;
}

bool Models_ExecutedOrderModel::isOddLotTradeIsSet() const
{
    return m_Is_odd_lot_tradeIsSet;
}

void Models_ExecutedOrderModel::unsetIs_odd_lot_trade()
{
    m_Is_odd_lot_tradeIsSet = false;
}
bool Models_ExecutedOrderModel::isIsTradeThroughExempt() const
{
    return m_Is_trade_through_exempt;
}

void Models_ExecutedOrderModel::setIsTradeThroughExempt(bool value)
{
    m_Is_trade_through_exempt = value;
    m_Is_trade_through_exemptIsSet = true;
}

bool Models_ExecutedOrderModel::isTradeThroughExemptIsSet() const
{
    return m_Is_trade_through_exemptIsSet;
}

void Models_ExecutedOrderModel::unsetIs_trade_through_exempt()
{
    m_Is_trade_through_exemptIsSet = false;
}
bool Models_ExecutedOrderModel::isIsSinglePriceCrossTrade() const
{
    return m_Is_single_price_cross_trade;
}

void Models_ExecutedOrderModel::setIsSinglePriceCrossTrade(bool value)
{
    m_Is_single_price_cross_trade = value;
    m_Is_single_price_cross_tradeIsSet = true;
}

bool Models_ExecutedOrderModel::isSinglePriceCrossTradeIsSet() const
{
    return m_Is_single_price_cross_tradeIsSet;
}

void Models_ExecutedOrderModel::unsetIs_single_price_cross_trade()
{
    m_Is_single_price_cross_tradeIsSet = false;
}
int32_t Models_ExecutedOrderModel::getSize() const
{
    return m_Size;
}

void Models_ExecutedOrderModel::setSize(int32_t value)
{
    m_Size = value;
    m_SizeIsSet = true;
}

bool Models_ExecutedOrderModel::sizeIsSet() const
{
    return m_SizeIsSet;
}

void Models_ExecutedOrderModel::unsetSize()
{
    m_SizeIsSet = false;
}
double Models_ExecutedOrderModel::getPrice() const
{
    return m_Price;
}

void Models_ExecutedOrderModel::setPrice(double value)
{
    m_Price = value;
    m_PriceIsSet = true;
}

bool Models_ExecutedOrderModel::priceIsSet() const
{
    return m_PriceIsSet;
}

void Models_ExecutedOrderModel::unsetPrice()
{
    m_PriceIsSet = false;
}
int64_t Models_ExecutedOrderModel::getTradeId() const
{
    return m_Trade_id;
}

void Models_ExecutedOrderModel::setTradeId(int64_t value)
{
    m_Trade_id = value;
    m_Trade_idIsSet = true;
}

bool Models_ExecutedOrderModel::tradeIdIsSet() const
{
    return m_Trade_idIsSet;
}

void Models_ExecutedOrderModel::unsetTrade_id()
{
    m_Trade_idIsSet = false;
}

}
}
}
}


