=begin
#Exchange Rates Realtime REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@apibricks.io
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::RateLimitApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RateLimitApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::RateLimitApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RateLimitApi' do
    it 'should create an instance of RateLimitApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::RateLimitApi)
    end
  end

  # unit tests for internal_ratelimit_wsconcon_apikey_get
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'internal_ratelimit_wsconcon_apikey_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for internal_ratelimit_wshello_ip_get
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'internal_ratelimit_wshello_ip_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for internal_ratelimit_wsreq_ip_get
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'internal_ratelimit_wsreq_ip_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
