=begin
#FinFeedAPI Stock REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@apibricks.io
Generated by: https://openapi-generator.tech
Generator version: 7.26.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::NativeIEXApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'NativeIEXApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::NativeIEXApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NativeIEXApi' do
    it 'should create an instance of NativeIEXApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::NativeIEXApi)
    end
  end

  # unit tests for v1_native_iex_admin_messages_symbol_get
  # Get Admin Messages
  # Streams one UTC day. &#x60;time_start&#x60; may be a full timestamp (&#x60;2026-09-28T13:31:14.8560065Z&#x60;) or a time of day (&#x60;13:31:14.8560065Z&#x60;) when &#x60;date&#x60; is set. Events start at that instant, inclusive. Omit &#x60;limit&#x60; to stream through the end of the day.
  # @param symbol The symbol identifier
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :date UTC day (&#x60;YYYY-MM-DD&#x60;). Optional when &#x60;time_start&#x60; includes a calendar day.
  # @option opts [String] :time_start Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when &#x60;date&#x60; is set.
  # @option opts [Integer] :limit Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
  # @return [Array<ModelsAdminMessageModel>]
  describe 'v1_native_iex_admin_messages_symbol_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_native_iex_admin_system_event_get
  # Get System Events
  # Streams one UTC day. &#x60;time_start&#x60; may be a full timestamp (&#x60;2026-09-28T13:31:14.8560065Z&#x60;) or a time of day (&#x60;13:31:14.8560065Z&#x60;) when &#x60;date&#x60; is set. Events start at that instant, inclusive. Omit &#x60;limit&#x60; to stream through the end of the day.
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :date UTC day (&#x60;YYYY-MM-DD&#x60;). Optional when &#x60;time_start&#x60; includes a calendar day.
  # @option opts [String] :time_start Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when &#x60;date&#x60; is set.
  # @option opts [Integer] :limit Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
  # @return [Array<IEXSystemEventSystemEventModel>]
  describe 'v1_native_iex_admin_system_event_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_native_iex_level1_quote_symbol_get
  # Get Level-1 Quotes
  # Streams one UTC day. &#x60;time_start&#x60; may be a full timestamp (&#x60;2026-09-28T13:31:14.8560065Z&#x60;) or a time of day (&#x60;13:31:14.8560065Z&#x60;) when &#x60;date&#x60; is set. Events start at that instant, inclusive. Omit &#x60;limit&#x60; to stream through the end of the day.
  # @param symbol The symbol identifier
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :date UTC day (&#x60;YYYY-MM-DD&#x60;). Optional when &#x60;time_start&#x60; includes a calendar day.
  # @option opts [String] :time_start Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when &#x60;date&#x60; is set.
  # @option opts [Integer] :limit Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
  # @return [Array<IEXQuoteUpdateQuoteUpdateModel>]
  describe 'v1_native_iex_level1_quote_symbol_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_native_iex_level2_price_level_update_symbol_get
  # Get Level-2 Price Level Book
  # Streams one UTC day. &#x60;time_start&#x60; may be a full timestamp (&#x60;2026-09-28T13:31:14.8560065Z&#x60;) or a time of day (&#x60;13:31:14.8560065Z&#x60;) when &#x60;date&#x60; is set. Events start at that instant, inclusive. Omit &#x60;limit&#x60; to stream through the end of the day.
  # @param symbol The symbol identifier
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :date UTC day (&#x60;YYYY-MM-DD&#x60;). Optional when &#x60;time_start&#x60; includes a calendar day.
  # @option opts [String] :time_start Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when &#x60;date&#x60; is set.
  # @option opts [Integer] :limit Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
  # @return [Array<IEXPriceLevelUpdatePriceLevelUpdateModel>]
  describe 'v1_native_iex_level2_price_level_update_symbol_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_native_iex_level3_order_book_symbol_get
  # Get Level-3 Order Book
  # Streams one UTC day. &#x60;time_start&#x60; may be a full timestamp (&#x60;2026-09-28T13:31:14.8560065Z&#x60;) or a time of day (&#x60;13:31:14.8560065Z&#x60;) when &#x60;date&#x60; is set. Events start at that instant, inclusive. Omit &#x60;limit&#x60; to stream through the end of the day.
  # @param symbol The symbol identifier
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :date UTC day (&#x60;YYYY-MM-DD&#x60;). Optional when &#x60;time_start&#x60; includes a calendar day.
  # @option opts [String] :time_start Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when &#x60;date&#x60; is set.
  # @option opts [Integer] :limit Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
  # @return [Array<ModelsOrderBookModel>]
  describe 'v1_native_iex_level3_order_book_symbol_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_native_iex_trade_symbol_get
  # Get Trades
  # Streams one UTC day. &#x60;time_start&#x60; may be a full timestamp (&#x60;2026-09-28T13:31:14.8560065Z&#x60;) or a time of day (&#x60;13:31:14.8560065Z&#x60;) when &#x60;date&#x60; is set. Events start at that instant, inclusive. Omit &#x60;limit&#x60; to stream through the end of the day.
  # @param symbol The symbol identifier
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :date UTC day (&#x60;YYYY-MM-DD&#x60;). Optional when &#x60;time_start&#x60; includes a calendar day.
  # @option opts [String] :time_start Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when &#x60;date&#x60; is set.
  # @option opts [Integer] :limit Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
  # @return [Array<IEXTradeTradeModel>]
  describe 'v1_native_iex_trade_symbol_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
