/*
 * Exchange Rates Historical REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using APIBricks.CoinAPI.ExchangeRatesAPI.Historical.REST.V1.Client;

namespace APIBricks.CoinAPI.ExchangeRatesAPI.Historical.REST.V1.Extensions
{
    /// <summary>
    /// Extension methods for IHostApplicationBuilder
    /// </summary>
    public static class IHostApplicationBuilderExtensions
    {
        /// <summary>
        /// Add the api to your application builder.
        /// </summary>
        /// <param name="builder"></param>
        /// <param name="options"></param>
        public static IHostApplicationBuilder ConfigureApi(this IHostApplicationBuilder builder, Action<HostConfiguration>? options = null)
        {
            HostConfiguration config = new(builder.Services);

            options?.Invoke(config);

            IServiceCollectionExtensions.AddApi(builder.Services, config);

            return builder;
        }
    }
}
