/**
 * FinFeedAPI Stock REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * NativeIEXApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_NativeIEXApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_NativeIEXApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/IEXPriceLevelUpdate_PriceLevelUpdateModel.h"
#include "CppRestOpenAPIClient/model/IEXQuoteUpdate_QuoteUpdateModel.h"
#include "CppRestOpenAPIClient/model/IEXSystemEvent_SystemEventModel.h"
#include "CppRestOpenAPIClient/model/IEXTrade_TradeModel.h"
#include "CppRestOpenAPIClient/model/Models_AdminMessageModel.h"
#include "CppRestOpenAPIClient/model/Models_OrderBookModel.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  NativeIEXApi 
{
public:

    explicit NativeIEXApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~NativeIEXApi();

    /// <summary>
    /// Get Admin Messages
    /// </summary>
    /// <remarks>
    /// Streaming endpoint. Use &#x60;limit&#x60; to cap the number of records returned (default 100, max 10000).
    /// </remarks>
    /// <param name="symbol">The symbol identifier</param>
    /// <param name="date">Date in format YYYY-MM-DD</param>
    /// <param name="limit">Maximum number of records to return (1-10000, default 100) (optional, default to 0)</param>
    pplx::task<std::vector<std::shared_ptr<Models_AdminMessageModel>>> v1NativeIexAdminMessagesSymbolGet(
        utility::string_t symbol,
        utility::datetime date,
        boost::optional<int32_t> limit
    ) const;
    /// <summary>
    /// Get System Events
    /// </summary>
    /// <remarks>
    /// Streaming endpoint. Use &#x60;limit&#x60; to cap the number of records returned (default 100, max 10000).
    /// </remarks>
    /// <param name="date">Date in format YYYY-MM-DD</param>
    /// <param name="limit">Maximum number of records to return (1-10000, default 100) (optional, default to 0)</param>
    pplx::task<std::vector<std::shared_ptr<IEXSystemEvent_SystemEventModel>>> v1NativeIexAdminSystemEventGet(
        utility::datetime date,
        boost::optional<int32_t> limit
    ) const;
    /// <summary>
    /// Get Level-1 Quotes
    /// </summary>
    /// <remarks>
    /// Streaming endpoint. Use &#x60;limit&#x60; to cap the number of records returned (default 100, max 10000).
    /// </remarks>
    /// <param name="symbol">The symbol identifier</param>
    /// <param name="date">Date in format YYYY-MM-DD</param>
    /// <param name="limit">Maximum number of records to return (1-10000, default 100) (optional, default to 0)</param>
    pplx::task<std::vector<std::shared_ptr<IEXQuoteUpdate_QuoteUpdateModel>>> v1NativeIexLevel1QuoteSymbolGet(
        utility::string_t symbol,
        utility::datetime date,
        boost::optional<int32_t> limit
    ) const;
    /// <summary>
    /// Get Level-2 Price Level Book
    /// </summary>
    /// <remarks>
    /// Streaming endpoint. Use &#x60;limit&#x60; to cap the number of records returned (default 100, max 10000).
    /// </remarks>
    /// <param name="symbol">The symbol identifier</param>
    /// <param name="date">Date in format YYYY-MM-DD</param>
    /// <param name="limit">Maximum number of records to return (1-10000, default 100) (optional, default to 0)</param>
    pplx::task<std::vector<std::shared_ptr<IEXPriceLevelUpdate_PriceLevelUpdateModel>>> v1NativeIexLevel2PriceLevelUpdateSymbolGet(
        utility::string_t symbol,
        utility::datetime date,
        boost::optional<int32_t> limit
    ) const;
    /// <summary>
    /// Get Level-3 Order Book
    /// </summary>
    /// <remarks>
    /// Streaming endpoint. Use &#x60;limit&#x60; to cap the number of records returned (default 100, max 10000).
    /// </remarks>
    /// <param name="symbol">The symbol identifier</param>
    /// <param name="date">Date in format YYYY-MM-DD</param>
    /// <param name="limit">Maximum number of records to return (1-10000, default 100) (optional, default to 0)</param>
    pplx::task<std::vector<std::shared_ptr<Models_OrderBookModel>>> v1NativeIexLevel3OrderBookSymbolGet(
        utility::string_t symbol,
        utility::datetime date,
        boost::optional<int32_t> limit
    ) const;
    /// <summary>
    /// Get Trades
    /// </summary>
    /// <remarks>
    /// Streaming endpoint. Use &#x60;limit&#x60; to cap the number of trade records returned (default 100, max 10000).
    /// </remarks>
    /// <param name="symbol">The symbol identifier</param>
    /// <param name="date">Date in format YYYY-MM-DD</param>
    /// <param name="limit">Maximum number of records to return (1-10000, default 100) (optional, default to 0)</param>
    pplx::task<std::vector<std::shared_ptr<IEXTrade_TradeModel>>> v1NativeIexTradeSymbolGet(
        utility::string_t symbol,
        utility::datetime date,
        boost::optional<int32_t> limit
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_NativeIEXApi_H_ */

