name: Publish python-rest package to the PyPi 
on:
  release:
    types: [created]
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-api/python-rest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          
      - name: install
        run: python -m pip install --user --upgrade setuptools wheel twine
       
      - name: setup package
        run: python setup.py sdist bdist_wheel
        
      - name: deploy
        run: python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }} || exit 0
        
