"""
    FinFeedAPI Stock REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: support@apibricks.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictInt, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from api_bricks_stock_api_rest.models.iex_price_level_update_price_level_update_model import IEXPriceLevelUpdatePriceLevelUpdateModel
from api_bricks_stock_api_rest.models.iex_quote_update_quote_update_model import IEXQuoteUpdateQuoteUpdateModel
from api_bricks_stock_api_rest.models.iex_system_event_system_event_model import IEXSystemEventSystemEventModel
from api_bricks_stock_api_rest.models.iex_trade_trade_model import IEXTradeTradeModel
from api_bricks_stock_api_rest.models.models_admin_message_model import ModelsAdminMessageModel
from api_bricks_stock_api_rest.models.models_order_book_model import ModelsOrderBookModel

from api_bricks_stock_api_rest.api_client import ApiClient, RequestSerialized
from api_bricks_stock_api_rest.api_response import ApiResponse
from api_bricks_stock_api_rest.rest import RESTResponseType


class NativeIEXApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def v1_native_iex_admin_messages_symbol_get(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[ModelsAdminMessageModel]:
        """Get Admin Messages

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_admin_messages_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[ModelsAdminMessageModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def v1_native_iex_admin_messages_symbol_get_with_http_info(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[ModelsAdminMessageModel]]:
        """Get Admin Messages

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_admin_messages_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[ModelsAdminMessageModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def v1_native_iex_admin_messages_symbol_get_without_preload_content(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Admin Messages

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_admin_messages_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[ModelsAdminMessageModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v1_native_iex_admin_messages_symbol_get_serialize(
        self,
        symbol,
        var_date,
        time_start,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if symbol is not None:
            _path_params['symbol'] = symbol
        # process the query parameters
        if var_date is not None:
            if isinstance(var_date, datetime):
                _query_params.append(
                    (
                        'date',
                        var_date.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('date', var_date))
            
        if time_start is not None:
            
            _query_params.append(('time_start', time_start))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKey', 
            'JWT'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/native/iex/admin/messages/{symbol}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def v1_native_iex_admin_system_event_get(
        self,
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[IEXSystemEventSystemEventModel]:
        """Get System Events

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_admin_system_event_get_serialize(
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[IEXSystemEventSystemEventModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def v1_native_iex_admin_system_event_get_with_http_info(
        self,
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[IEXSystemEventSystemEventModel]]:
        """Get System Events

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_admin_system_event_get_serialize(
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[IEXSystemEventSystemEventModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def v1_native_iex_admin_system_event_get_without_preload_content(
        self,
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get System Events

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_admin_system_event_get_serialize(
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[IEXSystemEventSystemEventModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v1_native_iex_admin_system_event_get_serialize(
        self,
        var_date,
        time_start,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if var_date is not None:
            if isinstance(var_date, datetime):
                _query_params.append(
                    (
                        'date',
                        var_date.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('date', var_date))
            
        if time_start is not None:
            
            _query_params.append(('time_start', time_start))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKey', 
            'JWT'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/native/iex/admin/system-event',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def v1_native_iex_level1_quote_symbol_get(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[IEXQuoteUpdateQuoteUpdateModel]:
        """Get Level-1 Quotes

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_level1_quote_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[IEXQuoteUpdateQuoteUpdateModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def v1_native_iex_level1_quote_symbol_get_with_http_info(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[IEXQuoteUpdateQuoteUpdateModel]]:
        """Get Level-1 Quotes

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_level1_quote_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[IEXQuoteUpdateQuoteUpdateModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def v1_native_iex_level1_quote_symbol_get_without_preload_content(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Level-1 Quotes

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_level1_quote_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[IEXQuoteUpdateQuoteUpdateModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v1_native_iex_level1_quote_symbol_get_serialize(
        self,
        symbol,
        var_date,
        time_start,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if symbol is not None:
            _path_params['symbol'] = symbol
        # process the query parameters
        if var_date is not None:
            if isinstance(var_date, datetime):
                _query_params.append(
                    (
                        'date',
                        var_date.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('date', var_date))
            
        if time_start is not None:
            
            _query_params.append(('time_start', time_start))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKey', 
            'JWT'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/native/iex/level1-quote/{symbol}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def v1_native_iex_level2_price_level_update_symbol_get(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[IEXPriceLevelUpdatePriceLevelUpdateModel]:
        """Get Level-2 Price Level Book

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_level2_price_level_update_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[IEXPriceLevelUpdatePriceLevelUpdateModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def v1_native_iex_level2_price_level_update_symbol_get_with_http_info(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[IEXPriceLevelUpdatePriceLevelUpdateModel]]:
        """Get Level-2 Price Level Book

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_level2_price_level_update_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[IEXPriceLevelUpdatePriceLevelUpdateModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def v1_native_iex_level2_price_level_update_symbol_get_without_preload_content(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Level-2 Price Level Book

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_level2_price_level_update_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[IEXPriceLevelUpdatePriceLevelUpdateModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v1_native_iex_level2_price_level_update_symbol_get_serialize(
        self,
        symbol,
        var_date,
        time_start,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if symbol is not None:
            _path_params['symbol'] = symbol
        # process the query parameters
        if var_date is not None:
            if isinstance(var_date, datetime):
                _query_params.append(
                    (
                        'date',
                        var_date.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('date', var_date))
            
        if time_start is not None:
            
            _query_params.append(('time_start', time_start))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKey', 
            'JWT'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/native/iex/level2-price-level-update/{symbol}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def v1_native_iex_level3_order_book_symbol_get(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[ModelsOrderBookModel]:
        """Get Level-3 Order Book

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_level3_order_book_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[ModelsOrderBookModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def v1_native_iex_level3_order_book_symbol_get_with_http_info(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[ModelsOrderBookModel]]:
        """Get Level-3 Order Book

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_level3_order_book_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[ModelsOrderBookModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def v1_native_iex_level3_order_book_symbol_get_without_preload_content(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Level-3 Order Book

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_level3_order_book_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[ModelsOrderBookModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v1_native_iex_level3_order_book_symbol_get_serialize(
        self,
        symbol,
        var_date,
        time_start,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if symbol is not None:
            _path_params['symbol'] = symbol
        # process the query parameters
        if var_date is not None:
            if isinstance(var_date, datetime):
                _query_params.append(
                    (
                        'date',
                        var_date.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('date', var_date))
            
        if time_start is not None:
            
            _query_params.append(('time_start', time_start))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKey', 
            'JWT'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/native/iex/level3-order-book/{symbol}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def v1_native_iex_trade_symbol_get(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[IEXTradeTradeModel]:
        """Get Trades

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_trade_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[IEXTradeTradeModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def v1_native_iex_trade_symbol_get_with_http_info(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[IEXTradeTradeModel]]:
        """Get Trades

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_trade_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[IEXTradeTradeModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def v1_native_iex_trade_symbol_get_without_preload_content(
        self,
        symbol: Annotated[StrictStr, Field(description="The symbol identifier")],
        var_date: Annotated[Optional[datetime], Field(description="UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.")] = None,
        time_start: Annotated[Optional[StrictStr], Field(description="Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Optional cap on the number of records (1-10000). Omit to stream through the end of the day.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Trades

        Streams one UTC day. `time_start` may be a full timestamp (`2026-09-28T13:31:14.8560065Z`) or a time of day (`13:31:14.8560065Z`) when `date` is set. Events start at that instant, inclusive. Omit `limit` to stream through the end of the day.

        :param symbol: The symbol identifier (required)
        :type symbol: str
        :param var_date: UTC day (`YYYY-MM-DD`). Optional when `time_start` includes a calendar day.
        :type var_date: datetime
        :param time_start: Inclusive start. Full ISO-8601 timestamp, or a UTC time of day when `date` is set.
        :type time_start: str
        :param limit: Optional cap on the number of records (1-10000). Omit to stream through the end of the day.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_native_iex_trade_symbol_get_serialize(
            symbol=symbol,
            var_date=var_date,
            time_start=time_start,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[IEXTradeTradeModel]",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v1_native_iex_trade_symbol_get_serialize(
        self,
        symbol,
        var_date,
        time_start,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if symbol is not None:
            _path_params['symbol'] = symbol
        # process the query parameters
        if var_date is not None:
            if isinstance(var_date, datetime):
                _query_params.append(
                    (
                        'date',
                        var_date.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('date', var_date))
            
        if time_start is not None:
            
            _query_params.append(('time_start', time_start))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKey', 
            'JWT'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/native/iex/trade/{symbol}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


